spring:
  application:
    name: cloudinary
    security:
      jwt:
        secret_key: ${JWT_SECRET_KEY}

  config:
    import: optional:file:.env[.properties],optional:none

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cache:
    type: redis

server:
  port: 8084

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

management:
  server:
    port: 8004
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,loggers,env
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

